# Название workflow, описывает его цель
name: Generate Changelog


# Указывает событие, при котором будет запускаться workflow
on:
  # Событие push в репозиторий
  push:
    # Указывает, что workflow будет запускаться только при пушах в ветку main
    branches:
      - main
    # Событие создания релиза
  release:
    types: [created]


# Определяет задачи, которые будут выполнены в рамках workflow
jobs:
  # Имя задачи, можно назвать по-другому, например, "update-changelog"
  build:
    # Запуск задачи на последней версии Ubuntu
    runs-on: ubuntu-latest


    # Шаги, которые необходимо выполнить в рамках задачи
    steps:
      # Использование действия checkout для клонирования репозитория
    - uses: actions/checkout@v4
      # Выкачивание всей истории коммитов, необходимо для корректной работы многих инструментов генерации changelog
      with:
        fetch-depth: 0

    - name: Generate a changelog
      uses: orhun/git-cliff-action@v3
      with:
        config: cliff.toml
        args: --verbose
      env:
        OUTPUT: CHANGELOG.md

    # Шаг для коммита изменений
    - name: Commit Changelog
      # Команды для выполнения
      run: |  
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add CHANGELOG.md
        git commit -m "Обновление CHANGELOG.md"
        git push https://github.com/${{ github.repository }}.git HEAD:main
